/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package android.support.coordinatorlayout;

public final class R {
    private R() {}

    public static final class attr {
        private attr() {}

        public static final int alpha = 0x7f030027;
        public static final int coordinatorLayoutStyle = 0x7f030064;
        public static final int font = 0x7f03007a;
        public static final int fontProviderAuthority = 0x7f03007c;
        public static final int fontProviderCerts = 0x7f03007d;
        public static final int fontProviderFetchStrategy = 0x7f03007e;
        public static final int fontProviderFetchTimeout = 0x7f03007f;
        public static final int fontProviderPackage = 0x7f030080;
        public static final int fontProviderQuery = 0x7f030081;
        public static final int fontStyle = 0x7f030082;
        public static final int fontVariationSettings = 0x7f030083;
        public static final int fontWeight = 0x7f030084;
        public static final int keylines = 0x7f030094;
        public static final int layout_anchor = 0x7f030097;
        public static final int layout_anchorGravity = 0x7f030098;
        public static final int layout_behavior = 0x7f030099;
        public static final int layout_dodgeInsetEdges = 0x7f0300c3;
        public static final int layout_insetEdge = 0x7f0300cc;
        public static final int layout_keyline = 0x7f0300cd;
        public static final int statusBarBackground = 0x7f030109;
        public static final int ttcIndex = 0x7f03013c;
    }
    public static final class color {
        private color() {}

        public static final int notification_action_color_filter = 0x7f05003f;
        public static final int notification_icon_bg_color = 0x7f050040;
        public static final int ripple_material_light = 0x7f05004b;
        public static final int secondary_text_default_material_light = 0x7f05004d;
    }
    public static final class dimen {
        private dimen() {}

        public static final int compat_button_inset_horizontal_material = 0x7f06004b;
        public static final